apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grafana-monitoring
  namespace: monitoring

resources:
  - namespace.yaml
  - persistent-volume.yaml
  - configmap.yaml
  - datasources.yaml
  - secret.yaml
  - dashboards-config.yaml
  - dashboards.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: depin-monitoring
  app.kubernetes.io/version: "10.2.0"

images:
  - name: grafana/grafana
    newTag: "10.2.0"

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: grafana
      namespace: monitoring
    spec:
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "3000"
            prometheus.io/path: "/metrics"