# Audit Log Forwarder for DePIN AI Compute Infrastructure
# This configuration forwards audit logs to centralized logging and SIEM systems

# DaemonSet to collect and forward audit logs from all nodes
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: depin-audit-forwarder
  namespace: depin-system
  labels:
    depin.ai/component: audit-forwarder
    depin.ai/tier: security
spec:
  selector:
    matchLabels:
      name: depin-audit-forwarder
  template:
    metadata:
      labels:
        name: depin-audit-forwarder
        depin.ai/component: audit-forwarder
    spec:
      serviceAccountName: depin-logging
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: audit-forwarder
        image: fluent/fluent-bit:2.1.10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: audit-logs
          mountPath: /var/log/audit
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc
          readOnly: true
        - name: tmp
          mountPath: /tmp
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch.depin-system.svc.cluster.local"
        - name: ELASTICSEARCH_PORT
          value: "9200"
      volumes:
      - name: audit-logs
        hostPath:
          path: /var/log/audit
          type: DirectoryOrCreate
      - name: config
        configMap:
          name: depin-audit-forwarder-config
      - name: tmp
        emptyDir: {}
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        kubernetes.io/os: linux

---
# ConfigMap for Fluent Bit audit log processing
apiVersion: v1
kind: ConfigMap
metadata:
  name: depin-audit-forwarder-config
  namespace: depin-system
  labels:
    depin.ai/component: audit-forwarder
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        storage.path  /tmp/flb-storage/
        storage.sync  normal
        storage.checksum off
        storage.backlog.mem_limit 5M

    [INPUT]
        Name              tail
        Path              /var/log/audit/audit.log
        Parser            audit_json
        Tag               audit.*
        Refresh_Interval  5
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        storage.type      filesystem

    [FILTER]
        Name    kubernetes
        Match   audit.*
        Kube_URL    https://kubernetes.default.svc:443
        Kube_CA_File    /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log       On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name                record_modifier
        Match               audit.*
        Record              cluster_name depin-ai-compute
        Record              node_name ${NODE_NAME}
        Record              pod_name ${POD_NAME}
        Record              pod_namespace ${POD_NAMESPACE}

    [FILTER]
        Name    grep
        Match   audit.*
        Regex   level (Request|RequestResponse|Metadata)

    [OUTPUT]
        Name            es
        Match           audit.*
        Host            ${ELASTICSEARCH_HOST}
        Port            ${ELASTICSEARCH_PORT}
        Index           depin-audit-logs
        Type            _doc
        Logstash_Format On
        Logstash_Prefix depin-audit
        Retry_Limit     5
        storage.total_limit_size 10M

    [OUTPUT]
        Name            forward
        Match           audit.*
        Host            siem-collector.depin-system.svc.cluster.local
        Port            24224
        storage.total_limit_size 5M

  parsers.conf: |
    [PARSER]
        Name        audit_json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep   On

---
# Service for audit forwarder metrics
apiVersion: v1
kind: Service
metadata:
  name: depin-audit-forwarder-metrics
  namespace: depin-system
  labels:
    depin.ai/component: audit-forwarder
    depin.ai/metrics: enabled
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 2020
    targetPort: 2020
    protocol: TCP
  selector:
    name: depin-audit-forwarder

---
# ServiceMonitor for Prometheus scraping
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: depin-audit-forwarder
  namespace: depin-system
  labels:
    depin.ai/component: audit-forwarder
spec:
  selector:
    matchLabels:
      depin.ai/component: audit-forwarder
  endpoints:
  - port: metrics
    interval: 30s
    path: /api/v1/metrics/prometheus