apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    app: fluent-bit
    component: config
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Plugins_File plugins.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 50MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Systemd_Filter _SYSTEMD_UNIT=docker.service
        Systemd_Filter _SYSTEMD_UNIT=containerd.service

    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_URL https://kubernetes.default.svc:443
        Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix kube.var.log.containers.
        Merge_Log On
        Merge_Log_Key log_processed
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off

    [FILTER]
        Name modify
        Match kube.*
        Add cluster_name depin-ai-compute
        Add datacenter primary

    [FILTER]
        Name grep
        Match kube.*
        Exclude kubernetes_namespace_name kube-system
        Exclude kubernetes_namespace_name kube-public

    # Parse DePIN AI compute specific logs
    [FILTER]
        Name parser
        Match kube.*ai-compute*
        Key_Name log
        Parser depin_ai_parser
        Reserve_Data On

    # Parse edge node logs
    [FILTER]
        Name parser
        Match kube.*edge*
        Key_Name log
        Parser depin_edge_parser
        Reserve_Data On

    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch.logging.svc.cluster.local
        Port 9200
        Index depin-logs
        Type _doc
        Logstash_Format On
        Logstash_Prefix depin
        Logstash_DateFormat %Y.%m.%d
        Include_Tag_Key On
        Tag_Key @tag
        Time_Key @timestamp
        Time_Key_Format %Y-%m-%dT%H:%M:%S.%L%z
        Retry_Limit 3

    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch.logging.svc.cluster.local
        Port 9200
        Index depin-system-logs
        Type _doc
        Logstash_Format On
        Logstash_Prefix depin-system
        Logstash_DateFormat %Y.%m.%d
        Include_Tag_Key On
        Tag_Key @tag
        Time_Key @timestamp

  parsers.conf: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On

    [PARSER]
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name depin_ai_parser
        Format regex
        Regex ^\[(?<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2})\]\s(?<level>[A-Z]+)\s(?<component>[^\s]+)\s(?<message>.*)$
        Time_Key timestamp
        Time_Format %Y-%m-%d %H:%M:%S

    [PARSER]
        Name depin_edge_parser
        Format json
        Time_Key timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Decode_Field_As json log

  plugins.conf: |
    [PLUGINS]
        Path /fluent-bit/bin/out_es.so