apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app: grafana
    component: datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
      jsonData:
        timeInterval: "5s"
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: monitoring
  labels:
    app: grafana
    component: dashboards-config
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-depin-dashboard
  namespace: monitoring
  labels:
    app: grafana
    component: dashboard
    dashboard: depin-overview
data:
  depin-overview.json: |
    {
      "dashboard": {
        "id": null,
        "title": "DePIN AI Compute Overview",
        "tags": ["depin", "ai", "compute"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "AI Compute Nodes Status",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=\"depin-ai-compute\"}",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "displayMode": "list",
                  "orientation": "horizontal"
                },
                "mappings": [],
                "thresholds": {
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 0
                    },
                    {
                      "color": "green",
                      "value": 1
                    }
                  ]
                }
              }
            },
            "options": {
              "reduceOptions": {
                "values": false,
                "calcs": ["lastNotNull"],
                "fields": ""
              },
              "orientation": "auto",
              "textMode": "auto",
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto"
            },
            "pluginVersion": "9.0.0",
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Edge Network Latency",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"depin-ai-compute\"}[5m]))",
                "refId": "A",
                "legendFormat": "95th percentile"
              },
              {
                "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket{job=\"depin-ai-compute\"}[5m]))",
                "refId": "B",
                "legendFormat": "50th percentile"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 0
            },
            "yAxes": [
              {
                "label": "Latency (seconds)",
                "min": 0
              },
              {
                "show": false
              }
            ]
          },
          {
            "id": 3,
            "title": "AI Workload Resource Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{namespace=\"ai-compute\"}[5m]) * 100",
                "refId": "A",
                "legendFormat": "CPU Usage %"
              },
              {
                "expr": "container_memory_usage_bytes{namespace=\"ai-compute\"} / 1024 / 1024 / 1024",
                "refId": "B",
                "legendFormat": "Memory Usage GB"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 8
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "10s",
        "schemaVersion": 27,
        "version": 1
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-kubernetes-dashboard
  namespace: monitoring
  labels:
    app: grafana
    component: dashboard
    dashboard: kubernetes-cluster
data:
  kubernetes-cluster.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Kubernetes Cluster Overview",
        "tags": ["kubernetes", "cluster", "infrastructure"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Cluster Nodes",
            "type": "stat",
            "targets": [
              {
                "expr": "kube_node_status_condition{condition=\"Ready\",status=\"true\"}",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "thresholds": {
                  "steps": [
                    {
                      "color": "red",
                      "value": null
                    },
                    {
                      "color": "green",
                      "value": 1
                    }
                  ]
                }
              }
            },
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Pod Status",
            "type": "piechart",
            "targets": [
              {
                "expr": "kube_pod_status_phase",
                "refId": "A"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 6,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "Namespace Resource Usage",
            "type": "table",
            "targets": [
              {
                "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (namespace)",
                "refId": "A",
                "format": "table"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 18,
              "y": 0
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s",
        "schemaVersion": 27,
        "version": 1
      }
    }