apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    security.depin.io/tier: system
    security.depin.io/monitoring: enabled
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
spec: {}